services:
  openchangelog:
    image: ghcr.io/jonashiltl/openchangelog:0.7.1
    ports:
      - "6001:6001"
    volumes:
      - type: bind
        source: ./openchangelog.yml
        target: /etc/openchangelog.yml
        read_only: true
      - type: bind
        source: ./release-notes
        target: /release-notes